#set document(
  title: "Menu Snap AI — Safety Design Report",
  author: "TAD Framework / ai-agent-architecture Domain Pack",
  date: datetime(year: 2026, month: 4, day: 2),
)

#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 2cm, right: 2cm),
  header: align(right)[
    #text(size: 9pt, fill: gray)[Menu Snap AI — Safety Design Report]
  ],
  footer: align(center)[
    #text(size: 9pt)[#context counter(page).display("1 / 1", both: true)]
  ],
)

#set text(size: 10pt)
#set heading(numbering: "1.1")
#set par(justify: true, leading: 0.7em)

// Title page
#align(center)[
  #v(3cm)
  #text(size: 28pt, weight: "bold")[Menu Snap AI]
  #v(0.3cm)
  #text(size: 18pt, fill: rgb("#555"))[Safety Design Report]
  #v(1cm)
  #line(length: 60%, stroke: 1pt + rgb("#C62828"))
  #v(0.5cm)
  #text(size: 12pt)[
    Agent: Food Recommendation Agent \
    Domain: Food / Allergy Safety \
    Capability: `safety_design` \
    Date: 2026-04-02
  ]
  #v(0.5cm)
  #text(size: 10pt, fill: rgb("#888"))[
    Generated by TAD Framework — ai-agent-architecture Domain Pack
  ]
]

#pagebreak()

// Table of contents
#outline(indent: 1.5em, depth: 3)

#pagebreak()

= Executive Summary

This report applies the *three-rail safety architecture* (input / execution / output rails) to Menu Snap AI, a food recommendation agent that analyzes menu photos and remembers user preferences. The *critical safety concern* is *allergy management*: recommending an allergenic food item is an irreversible, potentially life-threatening event.

#block(
  fill: rgb("#FFEBEE"),
  inset: 12pt,
  radius: 4pt,
  width: 100%,
)[
  *CRITICAL DESIGN DECISION:* Allergen filtering is implemented as an *architecture-level code filter* on every output — not as a prompt instruction. This filter runs outside the LLM and cannot be bypassed by prompt injection, memory poisoning, or model hallucination.
]

*Key findings from research:*
- Prompt injection attacks surged 340% in 2026; indirect injection accounts for 80%+ of attacks
- Memory poisoning can corrupt stored preferences — allergen profiles are highest-integrity data
- Annual economic cost of food allergies in the US: \$19--25 billion; severe reactions cause death
- Guardrails frameworks (NeMo, Guardrails AI) add 50--300ms latency — acceptable for food recommendation

= Risk Research

== AI Agent Security Landscape (2025--2026)

*Prompt injection* appeared in 73% of production AI deployments in 2025. For Menu Snap AI, the primary vector is *indirect injection via menu images* — adversarial text embedded in restaurant menus or photos that the OCR pipeline extracts and passes to the LLM.

*Memory poisoning* (documented by Microsoft Security, Feb 2026) allows attackers to inject persistent "facts" into an agent's memory. For a food agent, a poisoned preference like "user loves peanuts" overriding a real peanut allergy declaration is a *life-threatening scenario*.

*AI Recommendation Poisoning* enables restaurants to embed hidden prompts to bias recommendations — a commercial integrity risk.

== Guardrails Framework Comparison

#table(
  columns: (1fr, 1.5fr, 0.8fr, 1.2fr),
  inset: 8pt,
  align: (left, left, center, left),
  fill: (_, y) => if y == 0 { rgb("#E3F2FD") } else { none },
  [*Framework*], [*Approach*], [*Latency*], [*Best For*],
  [NeMo Guardrails], [Colang DSL, 5 rail types], [100--300ms], [Complex multi-rail policies],
  [Guardrails AI], [RAIL schema validation], [50--200ms], [Structured output validation],
  [Llama Guard], [Classification model], [~100ms], [Content safety classification],
)

*Recommendation:* Layered approach — NeMo-style rails for safety policy + schema validation for allergen data.

== Food / Allergy Domain Risks

- Allergen contamination can cause *anaphylaxis and death* — irreversible
- AI food safety models must be *auditable, explainable, and validated* under compliance standards
- False negatives in allergen detection *risk public health* — near-perfect accuracy required
- No specific AI food recommendation liability cases found in public record #text(fill: rgb("#E65100"))[\[UNVERIFIED\]]

= Threat Model: Three-Rail Analysis

== Input Rails

#table(
  columns: (1.2fr, 1.2fr, 1.2fr, 1fr),
  inset: 6pt,
  align: left,
  fill: (_, y) => if y == 0 { rgb("#FFCDD2") } else { none },
  [*Threat*], [*Mechanical Detection*], [*Cognitive Detection*], [*Response*],
  [Prompt injection via menu image], [OCR text pattern matching], [LLM classifier: "menu item or instruction?"], [Reject; use structured data only],
  [Allergen data poisoning], [Schema validation (FDA Top 9)], [LLM cross-check ingredients vs allergens], [Block until human verification],
  [PII in preferences], [Regex (email, phone, SSN)], [N/A], [Strip before storage],
  [Memory poisoning], [Preference change audit], [LLM consistency review], [*BLOCK allergen removal without re-confirmation*],
)

== Execution Rails

#table(
  columns: (1.2fr, 1.2fr, 1.2fr, 1fr),
  inset: 6pt,
  align: left,
  fill: (_, y) => if y == 0 { rgb("#FFF9C4") } else { none },
  [*Threat*], [*Mechanical Detection*], [*Cognitive Detection*], [*Response*],
  [Infinite loop], [Counter: max 3 retries], [N/A], [Circuit breaker],
  [Hallucinated menu items], [Schema: item in menu list?], [LLM verification], [Mark UNVERIFIED, do not recommend],
  [Incorrect nutrition info], [USDA FoodData API cross-ref], [LLM plausibility check], [Label "estimated" + disclaimer],
  [Tool abuse], [Rate limiter (10 calls/session)], [N/A], [Return cached results],
  [Cross-contamination blind spot], [High-risk restaurant type rule], [LLM shared-kitchen analysis], [Append warning for allergy users],
)

== Output Rails

#table(
  columns: (1.2fr, 1.2fr, 1.2fr, 1fr),
  inset: 6pt,
  align: left,
  fill: (_, y) => if y == 0 { rgb("#C8E6C9") } else { none },
  [*Threat*], [*Mechanical Detection*], [*Cognitive Detection*], [*Response*],
  [*Recommending allergenic food*], [*HARD BLOCK: ingredient-level filter vs allergen profile*], [LLM: "Could dish contain allergen even if unlisted?"], [*NEVER output. No override.*],
  [Misleading confidence], [Score < 0.8 if partial OCR], [LLM self-assessment], [Add "verify with staff"],
  [Data leakage], [Session isolation check], [N/A], [Strip + alert],
  [Unverified health claims], [Keyword filter], [LLM review], [Remove + add disclaimer],
)

= Human-in-the-Loop Boundaries

== Irreversibility Matrix

#table(
  columns: (1.5fr, 1fr, 1fr, 1.5fr),
  inset: 8pt,
  align: left,
  fill: (_, y) => if y == 0 { rgb("#E8EAF6") } else if y == 2 { rgb("#FFEBEE") } else { none },
  [*Operation*], [*Reversibility*], [*Impact*], [*Policy*],
  [Recommend a dish], [Low], [Individual], [Auto with output rails],
  [*Recommend to allergy user*], [*IRREVERSIBLE*], [*Life-threatening*], [*Architecture-level block*],
  [Save preference], [Reversible], [Individual], [Auto],
  [Modify allergen profile], [Semi-irreversible], [Life-threatening], [Human confirmation required],
  [Share recommendation], [Semi-reversible], [Social], [Human confirmation],
)

#block(
  fill: rgb("#FFF3E0"),
  inset: 12pt,
  radius: 4pt,
  width: 100%,
)[
  *Allergen Profile Modification Protocol:* When a user attempts to remove an allergen from their profile, the system requires explicit typed confirmation: _"You are removing Peanut from your allergy list. This means we will recommend peanut-containing dishes. Please type CONFIRM."_ This prevents accidental or socially-engineered removal.
]

== Circuit Breaker Design

#table(
  columns: (1.2fr, 0.8fr, 1.2fr, 1fr),
  inset: 6pt,
  align: left,
  fill: (_, y) => if y == 0 { rgb("#ECEFF1") } else { none },
  [*Trigger*], [*Transition*], [*Action*], [*Recovery*],
  [3 OCR failures], [CLOSED -> OPEN], [Return "try clearer photo"], [New photo (auto-reset)],
  [3 same-type errors], [CLOSED -> OPEN], [Stop, save state, notify user], [Auto-retry 60s (HALF-OPEN)],
  [Budget exceeded], [CLOSED -> OPEN], [Cached results only], [Daily reset / human approval],
  [Injection detected], [CLOSED -> OPEN], [Reject input, full log], [Human security review],
)

*State machine:* CLOSED #sym.arrow.r OPEN (3 failures) #sym.arrow.r HALF-OPEN (timeout 60s) #sym.arrow.r CLOSED (success) or back to OPEN (failure).

== Degradation Strategy (Fail-Closed)

#table(
  columns: (1fr, 1.5fr, 1.5fr),
  inset: 8pt,
  align: left,
  fill: (_, y) => if y == 0 { rgb("#FFCDD2") } else { none },
  [*Failure*], [*Degradation*], [*Rationale*],
  [Allergen service down], [*STOP all recommendations for allergy users*], [Fail-closed -- cannot risk allergenic food],
  [Vision/OCR unavailable], [Redirect to online menu], [Fail-closed on vision],
  [LLM engine down], [Plain menu list (no AI)], [Degrade to "menu viewer"],
  [Preference DB unavailable], [Treat as new user], [Fail-closed on personalization],
  [All services down], [Full stop + safety message], [Never guess],
)

== Audit Log Schema

Every safety decision is logged with: timestamp, session ID, user ID, event type (`recommendation_filtered`, `allergen_block`, `preference_change`, `circuit_breaker`, `injection_detected`), decision (allow/deny/escalate), context (input, allergen profile, matched allergen, confidence), reason, and outcome.

= Architecture Diagram

The three-rail architecture is visualized in the companion SVG file (`safety-architecture.svg`), showing:

+ *Input Rails* (red): OCR -> Injection Detection -> Schema Validation -> PII Scanner
+ *Execution Rails* (amber): LLM Engine -> Circuit Breaker -> Hallucination Check -> Cross-Contamination Warning
+ *Output Rails* (green): *Allergen Hard Filter* -> Confidence Scorer -> Health Claim Filter -> Disclaimer Engine
+ *Support Systems*: Allergen Profile DB, Audit Log, Human Ops escalation
+ *Circuit Breaker State Machine*: CLOSED -> OPEN -> HALF-OPEN -> CLOSED

The allergen filter (output rail) has a direct, non-bypassable connection to the User Allergen Profile DB.

= Conclusions and Recommendations

+ *Deploy allergen filtering as a code-level post-filter* — not an LLM prompt. This is the single most important safety decision.
+ *Use NeMo-style three-rail architecture* with mechanical (fast, reliable) + cognitive (flexible) detection at each rail.
+ *Fail-closed on all safety-related service failures.* An allergy user receiving no recommendation is infinitely safer than receiving a wrong one.
+ *Audit every safety decision.* Regulators and liability lawyers will ask for this.
+ *Require explicit confirmation for allergen profile changes.* Memory poisoning + social engineering must not silently remove an allergy.
+ *Add cross-contamination disclaimers* for all allergy users, regardless of specific dish ingredients — shared kitchens are a real risk.

#v(1cm)
#align(center)[
  #text(size: 9pt, fill: rgb("#888"))[
    Report generated by TAD Framework `safety_design` capability \
    ai-agent-architecture Domain Pack v1.0 \
    Sources verified via WebSearch on 2026-04-02
  ]
]
