#!/usr/bin/env bash
# tokens-to-css.sh — Level 0 token compiler (bash + jq only, no npm required)
# Usage: bash tools/tokens-to-css.sh <tokens.json> [> output.css]
#
# Input: JSON object with top-level keys (e.g. "primitive", "semantic", "component")
#        Each top-level value must be an object of token entries.
#        Token entries can be bare strings/numbers or objects with a "value" field.
#
# Output: CSS custom properties on :root

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: bash tokens-to-css.sh <tokens.json>" >&2
  echo "Example: bash tools/tokens-to-css.sh examples/starter-tokens.json > tokens.css" >&2
  exit 1
fi

TOKENS_FILE="$1"

if [ ! -f "$TOKENS_FILE" ]; then
  echo "Error: file not found: $TOKENS_FILE" >&2
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "Error: jq is required. Install: brew install jq" >&2
  exit 1
fi

# Validate top-level structure
if ! jq -e '. | type == "object"' "$TOKENS_FILE" &>/dev/null; then
  echo "Error: tokens file must be a JSON object" >&2
  exit 1
fi

# Validate all top-level group values are objects (not strings, arrays, etc.)
invalid_groups=$(jq -r 'to_entries[] | select(.value | type != "object") | .key' "$TOKENS_FILE" 2>/dev/null)
if [ -n "$invalid_groups" ]; then
  echo "Error: these top-level token groups are not objects: $invalid_groups" >&2
  echo "  Expected: {\"primitive\": {\"name\": \"value\"}, ...}" >&2
  exit 1
fi

# Generate CSS properties to a temp file so :root is only emitted on success
tmp_out=$(mktemp)
trap 'rm -f "$tmp_out"' EXIT

jq -r 'to_entries[] | . as $group |
  .value | to_entries[] | . as $entry |
  if $entry.value | type == "object" then
    if $entry.value | has("value") then
      "--\($group.key)-\($entry.key | gsub("[^a-zA-Z0-9_]"; "-")): \($entry.value.value | tostring);"
    else
      empty
    end
  else
    "--\($group.key)-\($entry.key | gsub("[^a-zA-Z0-9_]"; "-")): \($entry.value | tostring);"
  end' "$TOKENS_FILE" > "$tmp_out"

echo "/* Generated by tokens-to-css.sh */"
echo "/* Source: $TOKENS_FILE */"
echo ""
echo ":root {"
cat "$tmp_out"
echo "}"
echo ""
echo "/* Token groups: $(jq -r 'keys | join(", ")' "$TOKENS_FILE") */"
echo "/* Total tokens: $(jq '[to_entries[].value | to_entries[]] | length' "$TOKENS_FILE") */"
