#set page(paper: "a4", margin: 2cm)
#set text(font: "New Computer Modern", size: 11pt)

#align(center)[
  #text(size: 22pt, weight: "bold")[Standard Operating Procedure]
  #v(0.3em)
  #text(size: 16pt)[Wayo Prototype — Power-On Test]
  #v(0.3em)
  #text(size: 10pt, fill: gray)[SOP Version: 1.0 | Effective Date: 2026-04-02 | Author: TAD hw-testing Domain Pack]
]

#line(length: 100%)
#v(0.5em)

= 1. Purpose
This SOP defines the standard procedure for first power-on of a Wayo prototype board (ESP32-C3 + 5.65" E-ink + 18650 battery). It ensures safe power application and baseline measurements are recorded before any functional testing.

= 2. Scope
Applies to all Wayo prototype boards prior to functional or environmental testing.

= 3. Equipment Required
#table(
  columns: (1fr, 1fr),
  [*Equipment*], [*Specification*],
  [Bench power supply], [0–5V, 0–3A, current limiting capable],
  [Digital multimeter], [True RMS, uA range, 4.5+ digit],
  [USB-UART adapter], [3.3V logic level (CP2102, CH340, FTDI)],
  [Computer], [Python 3.8+, pyserial installed],
  [Anti-static wrist strap], [Connected to ESD mat / ground],
  [Magnifying glass], [10x minimum for solder joint inspection],
)

= 4. Safety Precautions
- *Always* use bench supply with current limit before connecting battery
- *Never* power board without completing pre-power checks
- *If smoke/heat detected*: disconnect power immediately, do not reconnect
- Wear ESD protection at all times when handling the board
- 18650 cells can deliver \>10A short-circuit current — handle with care

= 5. Procedure

== 5.1 Pre-Power Checks (5 minutes)
+ Visual inspection under magnification: solder bridges, missing/misaligned components
+ Measure resistance: VDD3P3 to GND (expect \>1k Ohm). *Short = DO NOT PROCEED*
+ Measure resistance: VBAT to GND (expect \>1k Ohm)
+ Set bench supply: 3.7V, *current limit = 100mA*
+ Verify ESD precautions in place

== 5.2 Initial Power-On (2 minutes)
+ Connect bench supply to battery input pads (observe polarity)
+ Enable output — monitor current display
+ Record initial current draw: \_\_\_\_ mA (expect \<50mA)
+ *Smoke test*: observe board for 10 seconds — heat, smoke, smell
+ If stable: increase current limit to 500mA

== 5.3 Rail Verification (5 minutes)
+ Measure each voltage rail per the checklist table
+ Record actual voltage values (not just PASS/FAIL)
+ Flag any rail \>+-3% as marginal, \>+-10% as FAIL

== 5.4 MCU Communication Check (3 minutes)
+ Connect USB-UART adapter (TX to RX, RX to TX, GND to GND)
+ Run: `python power-on-probe.py /dev/tty.usbserial-XXXX 115200`
+ Verify boot message received and logged

== 5.5 Record Results
+ Fill in power-on-results.md with all measurements
+ Fill in voltage-measurements.csv (generated by probe script)
+ Note any anomalies in the observations section

= 6. Acceptance Criteria
- All voltage rails within +-5% of nominal
- Quiescent current 19–29mA (24mA +-20%)
- No thermal anomalies
- MCU serial port responsive

= 7. Wayo-Specific Notes
- *E-ink display draws \<0.01uA in standby* (Waveshare spec) — does not affect power-on current
- ESP32-C3 active idle: ~24mA per Espressif documentation
- ESP32-C3 deep sleep: ~5uA typical (datasheet) — verified AFTER power-on test
- *Battery test comes AFTER bench supply verification* — 18650 has no current limit
- If solar charging circuit present: test with bench supply first, solar panel second

= 8. Revision History
#table(
  columns: (auto, auto, 1fr),
  [*Version*], [*Date*], [*Change*],
  [1.0], [2026-04-02], [Initial SOP created from hw-testing domain pack power_on_test capability],
)
