#!/usr/bin/env bash
# scan-packs.sh — Auto-generate pack-registry.yaml from .tad/capability-packs/
# Idempotent: overwrites pack-registry.yaml on each run.
# Usage: bash .tad/scripts/scan-packs.sh [--packs-dir=PATH]
#
# Type classification (architecture.md "Capability Pack Architecture Spectrum"):
#   reference-based: routing CAPABILITY.md → references/*.md
#   deep-skill:      interconnected SKILL.md files with cross-skill state
#   orchestration-router: state-machine router with phase transitions
#
# Keywords: single-line flow form only, e.g. keywords: ["a","b","c"]
# Block-list form (keywords:\n  - item) is not supported — keep keywords on one line.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TAD_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PACKS_DIR="$TAD_DIR/capability-packs"

# Parse arguments BEFORE computing OUTPUT (P0-1 fix: OUTPUT depends on final PACKS_DIR)
for arg in "$@"; do
  case "$arg" in
    --packs-dir=*) PACKS_DIR="${arg#--packs-dir=}"; PACKS_DIR_WAS_OVERRIDDEN=1 ;;
    --help|-h)
      echo "Usage: bash scan-packs.sh [--packs-dir=PATH]"
      echo "  --packs-dir=PATH  Override packs directory (default: .tad/capability-packs/)"
      exit 0
      ;;
  esac
done

# OUTPUT is derived from final PACKS_DIR (after arg parsing)
OUTPUT="$PACKS_DIR/pack-registry.yaml"

if [ ! -d "$PACKS_DIR" ]; then
  echo "ERROR: Packs directory not found: $PACKS_DIR" >&2
  exit 1
fi

# All packs declare `type:` in CAPABILITY.md frontmatter (P1-5 fix: TYPE_MAP removed).
# If a pack lacks the field, the default "reference-based" fires with a warning.
# To add a new pack type: add `type: {value}` to its CAPABILITY.md frontmatter.

# Extract YAML frontmatter field from CAPABILITY.md
# Matches single-line scalars only: fieldname: value (or "value")
# P2-2 hardening: anchors on "^field: " to avoid substring matches
extract_frontmatter_field() {
  local file="$1"
  local field="$2"
  awk '/^---$/{if(++n==2) exit} n==1 && /^'"$field"': /' "$file" \
    | sed "s/^${field}: *//" \
    | sed 's/^"//; s/"$//' \
    | head -1
}

# Extract keywords array from CAPABILITY.md frontmatter
# Single-line flow form only: keywords: ["a","b"]
# P1-1 note: block-list form not supported — constraint documented in header
extract_keywords() {
  local file="$1"
  awk '/^---$/{if(++n==2) exit} n==1 && /^keywords: /' "$file" \
    | sed 's/^keywords: *//' \
    | head -1
}

# Extract CONSUMES line from CAPABILITY.md body (after frontmatter)
# P1-2 fix: removed dead-code sed patterns for blockquote stripping and period-truncation
# P1-3 fix: use result=$() assignment for reliable fallback under set -e
extract_consumes() {
  local result
  result=$(grep -m1 '^\*\*CONSUMES\*\*:' "$1" 2>/dev/null \
    | sed 's/^\*\*CONSUMES\*\*: *//' \
    | head -1)
  echo "${result:-Not specified}"
}

# Extract PRODUCES line from CAPABILITY.md body (after frontmatter)
# P1-3 fix: use result=$() assignment for reliable fallback under set -e
extract_produces() {
  local result
  result=$(grep -m1 '^\*\*PRODUCES\*\*:' "$1" 2>/dev/null \
    | sed 's/^\*\*PRODUCES\*\*: *//' \
    | head -1)
  echo "${result:-Not specified}"
}

# Write header
cat > "$OUTPUT" << 'HEADER'
# Auto-generated by scan-packs.sh — do not edit manually
# Registry status rows are derived from CAPABILITY.md frontmatter (status: active|frozen) — do not hand-edit status
# Re-generate: bash .tad/scripts/scan-packs.sh after editing any CAPABILITY.md
HEADER

# Auto-detect source_repo from git remote (AC5 — not hardcoded, works for forks/renames)
# P1-1 fix: strip credentials from HTTPS URL before normalization;
#           only set SOURCE_REPO for known github.com hosts (avoid non-github leakage)
# P1-2 fix: treat detached HEAD ("HEAD") as "main" for safe gh/curl URLs
SOURCE_REPO=""
SOURCE_BRANCH=""
if git -C "$TAD_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  raw_url=$(git -C "$TAD_DIR" remote get-url origin 2>/dev/null || true)
  if [ -n "$raw_url" ]; then
    # Strip credential-bearing HTTPS prefix (e.g. https://x-access-token:TOKEN@github.com/...)
    raw_url=$(echo "$raw_url" | sed -E 's#^(https?://)[^@]+@#\1#')
    # Only normalize GitHub.com URLs; leave SOURCE_REPO empty for other hosts (triggers AC6 fallback)
    case "$raw_url" in
      git@github.com:*|https://github.com/*)
        SOURCE_REPO=$(echo "$raw_url" | sed \
          -e 's#^git@github\.com:##' \
          -e 's#^https://github\.com/##' \
          -e 's#\.git$##')
        ;;
      *)
        SOURCE_REPO=""
        ;;
    esac
    # P1-2: rev-parse --abbrev-ref HEAD returns "HEAD" in detached state — fall back to "main"
    _branch=$(git -C "$TAD_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")
    [ "$_branch" = "HEAD" ] && SOURCE_BRANCH="main" || SOURCE_BRANCH="$_branch"
  fi
fi

# Read version from .tad/version.txt (if exists)
SYNCED_VERSION=""
if [ -f "$TAD_DIR/version.txt" ]; then
  SYNCED_VERSION=$(cat "$TAD_DIR/version.txt" | tr -d '[:space:]')
fi

# P1-5 fix: use UTC date
cat >> "$OUTPUT" << EOF
version: 1.0.0
last_scanned: "$(date -u +%Y-%m-%d)"
source_repo: "${SOURCE_REPO}"
source_branch: "${SOURCE_BRANCH}"
source_base_path: ".tad/capability-packs"
synced_from_version: "${SYNCED_VERSION}"  # reserved for cross-version compatibility checks (Phase 2 consumer TBD)
packs:
EOF

count=0
pack_names=""
for cap_file in "$PACKS_DIR"/*/CAPABILITY.md; do
  [ -f "$cap_file" ] || continue

  pack_dir="$(dirname "$cap_file")"
  pack_name="$(basename "$pack_dir")"
  pack_names="$pack_names $pack_name"

  # Extract fields
  name=$(extract_frontmatter_field "$cap_file" "name")
  description=$(extract_frontmatter_field "$cap_file" "description")
  keywords=$(extract_keywords "$cap_file")
  consumes=$(extract_consumes "$cap_file")
  produces=$(extract_produces "$cap_file")

  # Read type from CAPABILITY.md frontmatter (declarative single-source-of-truth)
  declared_type=$(extract_frontmatter_field "$cap_file" "type" 2>/dev/null || true)
  if [ -n "$declared_type" ]; then
    pack_type="$declared_type"
  else
    echo "WARNING: $pack_name missing 'type:' in frontmatter — defaulting to reference-based" >&2
    pack_type="reference-based"
  fi

  # Durable freeze flag lives on CAPABILITY.md frontmatter (status: active|frozen).
  # A missing status counts as active. Never hand-edit the emitted status rows —
  # edit the pack's CAPABILITY.md frontmatter and re-run this script.
  pack_status=$(extract_frontmatter_field "$cap_file" "status" 2>/dev/null || true)
  case "$pack_status" in
    frozen|active) ;;
    *) pack_status="active" ;;
  esac

  # Relative path from TAD root
  rel_path=".tad/capability-packs/${pack_name}/"

  # Escape double quotes for YAML string safety
  description_safe="${description//\"/\\\"}"
  consumes_safe="${consumes//\"/\\\"}"
  produces_safe="${produces//\"/\\\"}"

  # Emit YAML entry
  cat >> "$OUTPUT" << EOF
  - name: "${name:-$pack_name}"
    description: "${description_safe:-No description}"
    path: "${rel_path}"
    consumes: "${consumes_safe}"
    produces: "${produces_safe}"
    keywords: ${keywords:-[]}
    type: "${pack_type}"
    status: "${pack_status}"
EOF

  count=$((count + 1))
done

# --- Registry↔projection consistency assertion ---
# pack 计数以登记面为准：登记面 ＝ pack-registry.yaml 条目且源包有 CAPABILITY.md 的 pack 集合；目录数不是登记数——无 CAPABILITY.md 的目录（如 agent-computer-interface）不计入登记数。凡计数类 AC 必须在方法文中写明计数对象定义。
# Every registered pack MUST have a projection at
# <root>/.agents/skills/<name>/SKILL.md. Missing projection = red.
if [ -n "${PACKS_DIR_WAS_OVERRIDDEN:-}" ]; then
  ASSERT_ROOT="$(cd "$PACKS_DIR/../.." 2>/dev/null && pwd -P)"
else
  ASSERT_ROOT="$(cd "$TAD_DIR/.." 2>/dev/null && pwd -P)"
fi
SKILLS_DIR="$ASSERT_ROOT/.agents/skills"
if [ -d "$SKILLS_DIR" ]; then
  missing=""
  for pname in $pack_names; do
    [ -f "$SKILLS_DIR/$pname/SKILL.md" ] || missing="$missing $pname"
  done
  if [ -n "$missing" ]; then
    echo "ERROR: registered pack(s) missing .agents/skills projection:$missing" >&2
    exit 1
  fi
else
  echo "NOTE: no .agents/skills tree at $SKILLS_DIR - projection assertion skipped" >&2
fi
echo "scan-packs.sh: scanned $count packs → $OUTPUT"
