#!/usr/bin/env python3
"""Quantitative image analysis tools for academic research.

Five subcommands:
  edges      Edge/contour extraction → SVG export
  colors     Color histogram analysis → JSON
  match      Cross-image ORB/SIFT feature matching → JSON
  frequency  Fourier transform for repeating pattern detection → JSON
  features   Feature vector extraction for statistical clustering → JSON
"""

import argparse
import json
import os
import sys
from pathlib import Path

import cv2
import numpy as np


def validate_path(path_str):
    """Validate file path: must exist, reject traversal components in raw input."""
    if ".." in Path(path_str).parts:
        print(f"ERROR: Path traversal detected (contains '..'): {path_str}", file=sys.stderr)
        sys.exit(1)
    real = os.path.realpath(path_str)
    if not os.path.exists(real):
        print(f"ERROR: File not found: {path_str}", file=sys.stderr)
        sys.exit(1)
    return real


def validate_output_path(path_str):
    """Validate output path: reject traversal, create parent if needed."""
    if ".." in Path(path_str).parts:
        print(f"ERROR: Path traversal detected in output (contains '..'): {path_str}", file=sys.stderr)
        sys.exit(1)
    real = os.path.realpath(path_str)
    parent = Path(real).parent
    if not parent.exists():
        parent.mkdir(parents=True, exist_ok=True)
    return real


def write_json(data, output_path):
    """Write JSON output with consistent formatting."""
    with open(output_path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Output written to: {output_path}")


# ── edges ──────────────────────────────────────────────────────────

def cmd_edges(args):
    """Edge/contour extraction → SVG."""
    img_path = validate_path(args.input)
    out_path = validate_output_path(args.output)

    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print(f"ERROR: Cannot read image: {img_path}", file=sys.stderr)
        sys.exit(1)

    h, w = img.shape
    threshold = args.threshold

    blurred = cv2.GaussianBlur(img, (5, 5), 1.4)
    edges = cv2.Canny(blurred, threshold, threshold * 2)
    contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    svg_paths = []
    for contour in contours:
        if len(contour) < 3:
            continue
        points = contour.squeeze()
        if points.ndim < 2:
            continue
        d = f"M {points[0][0]} {points[0][1]}"
        for pt in points[1:]:
            d += f" L {pt[0]} {pt[1]}"
        d += " Z"
        svg_paths.append(f'  <path d="{d}" fill="none" stroke="black" stroke-width="1"/>')

    svg_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">
  <!-- Generated by academic-research image-analysis.py edges -->
  <!-- Source: {os.path.basename(img_path).replace('--', '- -').replace('&', '&amp;').replace('<', '&lt;')} | Threshold: {threshold} | Contours: {len(svg_paths)} -->
{chr(10).join(svg_paths)}
</svg>"""

    with open(out_path, "w") as f:
        f.write(svg_content)
    print(f"Output written to: {out_path}")
    print(f"  Image: {w}x{h}, Threshold: {threshold}, Contours: {len(svg_paths)}")


# ── colors ─────────────────────────────────────────────────────────

def cmd_colors(args):
    """Color histogram analysis → JSON."""
    img_path = validate_path(args.input)
    out_path = validate_output_path(args.output)

    img = cv2.imread(img_path)
    if img is None:
        print(f"ERROR: Cannot read image: {img_path}", file=sys.stderr)
        sys.exit(1)

    h, w = img.shape[:2]
    bins = args.bins

    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    hist_h = cv2.calcHist([hsv], [0], None, [bins], [0, 180]).flatten()
    hist_s = cv2.calcHist([hsv], [1], None, [bins], [0, 256]).flatten()
    hist_v = cv2.calcHist([hsv], [2], None, [bins], [0, 256]).flatten()

    total_pixels = h * w
    histogram = []
    for i in range(bins):
        histogram.append({
            "bin_index": i,
            "hue": {"bin_start": round(i * 180 / bins, 1), "bin_end": round((i + 1) * 180 / bins, 1), "count": int(hist_h[i])},
            "saturation": {"bin_start": round(i * 256 / bins, 1), "bin_end": round((i + 1) * 256 / bins, 1), "count": int(hist_s[i])},
            "value": {"bin_start": round(i * 256 / bins, 1), "bin_end": round((i + 1) * 256 / bins, 1), "count": int(hist_v[i])},
        })

    rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    pixels = rgb.reshape(-1, 3).astype(np.float32)
    k = 5
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 20, 1.0)
    try:
        _, labels, centers = cv2.kmeans(pixels, k, None, criteria, 3, cv2.KMEANS_RANDOM_CENTERS)
    except cv2.error:
        k = 2
        _, labels, centers = cv2.kmeans(pixels, k, None, criteria, 3, cv2.KMEANS_RANDOM_CENTERS)

    dominant_colors = []
    for i, center in enumerate(centers):
        r, g, b = int(center[0]), int(center[1]), int(center[2])
        count = int(np.sum(labels == i))
        dominant_colors.append({
            "hex": f"#{r:02x}{g:02x}{b:02x}",
            "rgb": [r, g, b],
            "percentage": round(count / total_pixels * 100, 2),
        })
    dominant_colors.sort(key=lambda c: c["percentage"], reverse=True)

    result = {
        "image": os.path.basename(img_path),
        "dimensions": {"width": w, "height": h},
        "bins": bins,
        "total_pixels": total_pixels,
        "histogram": histogram,
        "dominant_colors": dominant_colors,
    }
    write_json(result, out_path)


# ── match ──────────────────────────────────────────────────────────

def cmd_match(args):
    """Cross-image feature matching → JSON."""
    img1_path = validate_path(args.image1)
    img2_path = validate_path(args.image2)
    out_path = validate_output_path(args.output)

    img1 = cv2.imread(img1_path, cv2.IMREAD_GRAYSCALE)
    img2 = cv2.imread(img2_path, cv2.IMREAD_GRAYSCALE)
    if img1 is None or img2 is None:
        print("ERROR: Cannot read one or both images", file=sys.stderr)
        sys.exit(1)

    method = args.method.lower()
    if method == "sift":
        try:
            detector = cv2.SIFT_create()
        except AttributeError:
            print("WARNING: SIFT not available in this OpenCV build. Falling back to ORB.", file=sys.stderr)
            detector = cv2.ORB_create(nfeatures=1000)
            method = "orb"
        norm_type = cv2.NORM_L2
    else:
        detector = cv2.ORB_create(nfeatures=1000)
        norm_type = cv2.NORM_HAMMING

    kp1, desc1 = detector.detectAndCompute(img1, None)
    kp2, desc2 = detector.detectAndCompute(img2, None)

    if desc1 is None or desc2 is None or len(kp1) == 0 or len(kp2) == 0:
        result = {
            "image1": os.path.basename(img1_path),
            "image2": os.path.basename(img2_path),
            "method": method,
            "keypoints1": len(kp1) if kp1 else 0,
            "keypoints2": len(kp2) if kp2 else 0,
            "matches": 0,
            "good_matches": 0,
            "similarity_score": 0.0,
            "matched_keypoints": [],
        }
        write_json(result, out_path)
        return

    bf = cv2.BFMatcher(norm_type)
    raw_matches = bf.knnMatch(desc1, desc2, k=2)

    good = []
    for pair in raw_matches:
        if len(pair) == 2:
            m, n = pair
            if m.distance < 0.75 * n.distance:
                good.append(m)

    max_possible = min(len(kp1), len(kp2))
    similarity = round(len(good) / max_possible, 4) if max_possible > 0 else 0.0

    matched_kps = []
    for m in good[:50]:
        p1 = kp1[m.queryIdx].pt
        p2 = kp2[m.trainIdx].pt
        matched_kps.append({
            "x1": round(p1[0], 1), "y1": round(p1[1], 1),
            "x2": round(p2[0], 1), "y2": round(p2[1], 1),
            "distance": round(float(m.distance), 4),
        })

    result = {
        "image1": os.path.basename(img1_path),
        "image2": os.path.basename(img2_path),
        "method": method,
        "keypoints1": len(kp1),
        "keypoints2": len(kp2),
        "matches": len(raw_matches),
        "good_matches": len(good),
        "similarity_score": similarity,
        "matched_keypoints": matched_kps,
    }
    write_json(result, out_path)


# ── frequency ──────────────────────────────────────────────────────

def cmd_frequency(args):
    """Fourier frequency analysis → JSON."""
    img_path = validate_path(args.input)
    out_path = validate_output_path(args.output)

    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print(f"ERROR: Cannot read image: {img_path}", file=sys.stderr)
        sys.exit(1)

    h, w = img.shape
    f_transform = np.fft.fft2(img.astype(np.float64))
    f_shift = np.fft.fftshift(f_transform)
    magnitude = np.abs(f_shift)

    center_y, center_x = h // 2, w // 2
    magnitude[center_y - 2:center_y + 3, center_x - 2:center_x + 3] = 0

    threshold = np.percentile(magnitude, 99.5)
    peak_locs = np.argwhere(magnitude > threshold)

    dominant = []
    for loc in peak_locs[:20]:
        fy = loc[0] - center_y
        fx = loc[1] - center_x
        freq_dist = np.sqrt(fx**2 + fy**2)
        if freq_dist < 1:
            continue
        period_px = round(max(h, w) / freq_dist, 1)
        dominant.append({
            "freq_x": int(fx),
            "freq_y": int(fy),
            "magnitude": round(float(magnitude[loc[0], loc[1]]), 2),
            "period_px": period_px,
        })

    dominant.sort(key=lambda d: d["magnitude"], reverse=True)

    out_p = Path(out_path)
    power_path = str(out_p.with_name(out_p.stem + "_power_spectrum.png"))
    log_magnitude = np.log1p(magnitude)
    max_val = log_magnitude.max()
    if max_val > 0:
        normalized = (log_magnitude / max_val * 255).astype(np.uint8)
    else:
        normalized = np.zeros_like(log_magnitude, dtype=np.uint8)
    cv2.imwrite(power_path, normalized)

    result = {
        "image": os.path.basename(img_path),
        "dimensions": {"width": w, "height": h},
        "dominant_frequencies": dominant[:10],
        "power_spectrum_path": os.path.basename(power_path),
        "analysis_note": "period_px < 50 = fine texture, 50-200 = medium pattern, > 200 = large motif",
    }
    write_json(result, out_path)


# ── features ───────────────────────────────────────────────────────

def cmd_features(args):
    """Feature vector extraction for clustering → JSON."""
    img_path = validate_path(args.input)
    out_path = validate_output_path(args.output)

    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print(f"ERROR: Cannot read image: {img_path}", file=sys.stderr)
        sys.exit(1)

    method = args.method.lower()
    if method == "sift":
        try:
            detector = cv2.SIFT_create()
        except AttributeError:
            print("WARNING: SIFT not available. Falling back to ORB.", file=sys.stderr)
            detector = cv2.ORB_create(nfeatures=500)
            method = "orb"
    else:
        detector = cv2.ORB_create(nfeatures=500)

    kp, descriptors = detector.detectAndCompute(img, None)

    if descriptors is None or len(kp) == 0:
        vector = []
    else:
        vector = np.mean(descriptors, axis=0).tolist()
        vector = [round(v, 4) for v in vector]

    result = {
        "image": os.path.basename(img_path),
        "method": method,
        "keypoint_count": len(kp) if kp else 0,
        "dimensions": len(vector),
        "vector": vector,
        "note": "Mean descriptor vector. Use cosine similarity for comparing feature vectors across images.",
    }
    write_json(result, out_path)


# ── CLI ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Quantitative image analysis tools for academic research.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""subcommands:
  edges      Edge/contour extraction → SVG
  colors     Color histogram analysis → JSON
  match      Cross-image feature matching → JSON
  frequency  Fourier frequency analysis → JSON
  features   Feature vector extraction → JSON

examples:
  %(prog)s edges artifact.jpg --output contours.svg
  %(prog)s colors painting.png --output palette.json --bins 16
  %(prog)s match bowl_A.jpg bowl_B.jpg --output similarity.json
  %(prog)s frequency textile.jpg --output pattern_freq.json
  %(prog)s features artifact.jpg --output cluster_input.json
""",
    )
    subparsers = parser.add_subparsers(dest="command", help="Analysis subcommand")

    p_edges = subparsers.add_parser("edges", help="Edge/contour extraction → SVG")
    p_edges.add_argument("input", help="Input image path")
    p_edges.add_argument("--output", required=True, help="Output SVG path")
    p_edges.add_argument("--threshold", type=int, default=100, help="Canny threshold (default: 100)")

    p_colors = subparsers.add_parser("colors", help="Color histogram analysis → JSON")
    p_colors.add_argument("input", help="Input image path")
    p_colors.add_argument("--output", required=True, help="Output JSON path")
    p_colors.add_argument("--bins", type=int, default=32, help="Histogram bins (default: 32)")

    p_match = subparsers.add_parser("match", help="Cross-image feature matching → JSON")
    p_match.add_argument("image1", help="First image path")
    p_match.add_argument("image2", help="Second image path")
    p_match.add_argument("--output", required=True, help="Output JSON path")
    p_match.add_argument("--method", choices=["orb", "sift"], default="orb", help="Feature detector (default: orb)")

    p_freq = subparsers.add_parser("frequency", help="Fourier frequency analysis → JSON")
    p_freq.add_argument("input", help="Input image path")
    p_freq.add_argument("--output", required=True, help="Output JSON path")

    p_feat = subparsers.add_parser("features", help="Feature vector extraction → JSON")
    p_feat.add_argument("input", help="Input image path")
    p_feat.add_argument("--output", required=True, help="Output JSON path")
    p_feat.add_argument("--method", choices=["orb", "sift"], default="orb", help="Feature detector (default: orb)")

    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        sys.exit(1)

    commands = {
        "edges": cmd_edges,
        "colors": cmd_colors,
        "match": cmd_match,
        "frequency": cmd_frequency,
        "features": cmd_features,
    }
    commands[args.command](args)


if __name__ == "__main__":
    main()
